apiVersion: v1
kind: Secret
metadata:
  name: fiap-db-secret
  namespace: fiap-soat11
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=___DB_HOST___;Port=3306;Database=fiapx;Uid=user_fiap;Pwd=pass_fiap;"